name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.platform }} / ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        platform: [clj, cljs]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Clojure tools
      uses: DeLaGuardo/setup-clojure@13.2
      with:
        cli: latest

    - name: Install Node.js
      if: matrix.platform == 'cljs'
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install npm dependencies
      if: matrix.platform == 'cljs'
      run: npm ci

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.cljs/.aot_cache
        key: ${{ runner.os }}-${{ matrix.platform }}-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.platform }}-

    - name: Run tests
      run: clojure -M:libs:test --focus :${{ matrix.platform }}
